# Generated by Django 4.1.5 on 2023-02-04 17:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patinete',
            fields=[
                ('numero', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('precio_desbloque', models.FloatField()),
                ('precio_minuto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('matricula', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('Coche', 'Coche'), ('Ciclomotor', 'Ciclomotor'), ('Motocicleta', 'Motocicleta')], default='Coche', max_length=11)),
                ('chasis', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('modelo', models.CharField(max_length=40)),
                ('color', models.CharField(choices=[('Negro', 'Negro'), ('Rojo', 'Rojo'), ('Gris', 'Gris'), ('Azul', 'Azul')], default='Negro', max_length=30)),
                ('fecha_fabrica', models.DateField()),
                ('fecha_matricula', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('suspendido', models.BooleanField(default=False)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debito', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desbloqueo', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('coste_final', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('patinete', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.patinete')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.usuario')),
            ],
        ),
    ]
