# Generated by Django 4.1.5 on 2023-01-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fecha_matricula',
            field=models.DateField(blank=True, null=True),
        ),
    ]
