# Generated by Django 4.1.7 on 2023-02-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='puntuacion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
