# Generated by Django 4.1.5 on 2023-01-29 18:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_vehiculo_fecha_baja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patinete',
            fields=[
                ('numero', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('precio_desbloque', models.FloatField(verbose_name=[django.core.validators.MinValueValidator(0.1)])),
                ('precio_minuto', models.FloatField(verbose_name=[django.core.validators.MinValueValidator(0.1)])),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debito', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desbloqueo', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('coste_final', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('patinete', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.patinete')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.usuario')),
            ],
        ),
    ]
