# Generated by Django 4.1.5 on 2023-01-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_patinete_usuario_alquiler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['marca']},
        ),
    ]
